### ISSUE TITLE
contributor information

### ISSUE THREAD

**Issue by ghost** [silmerusse/fudge_pathfinding#2]
Hi Rick

I am A student who benefits from your work, because your open source A-Star algorithm in Github makes my experiment easier. I used your open source code in my paper, but I cannot get further information about you, so I write this email specially, hoping that you can provide the university or company where you study or work and the name of the author if it is convenient for you. In order to be able to quote your work and express thanks to you in my paper.

thanks

**Comment by silmerusse** [comment]
My name is Hu, Yu graduated from Shanghai Jiao Tong University. For other personal information I would like to keep private.
